### ISSUE TITLE
use the tools.deps built-in resolver, rather than custom

### ISSUE THREAD

**Issue by sinistral** [StediInc/cdk-clj#36]
The [custom deps resolution](https://github.com/StediInc/cdk-clj/blob/master/src/stedi/cdk/lambda/build.clj#L86-L93) in the Lambda build is [brittle](https://github.com/StediInc/cdk-clj/pull/35).  @tvanhens [suggests](https://github.com/StediInc/cdk-clj/pull/35#pullrequestreview-289579281) using [tools.deps](https://github.com/clojure/tools.deps.alpha/blob/master/src/main/clojure/clojure/tools/deps/alpha/reader.clj#L100-L106) own, more-robust mechanism, which would be ... more robust.

**Comment by tvanhens** [comment]
This is no longer relevant due to using `stedi/lambda` for builds now which relies on `pack` to handle dependency resolution.
