### ISSUE TITLE
Upgrade to cdk 1.7

### ISSUE THREAD

**Issue by enocom** [StediInc/cdk-clj#6]
https://github.com/aws/aws-cdk/blob/master/CHANGELOG.md#150-2019-08-20

**Comment by klang** [comment]
cdk 1.9 .. cdk is a moving target at the moment, a new version is released every week :-)

**Comment by enocom** [comment]
It might be worth automating the upgrade. A bot could send PRs everytime a new version of cdk is available. 

/cc @tvanhens
