### ISSUE TITLE
Example in README.md fails with host key not found error

### ISSUE THREAD

**Issue by tpot** [StediInc/cdk-clj#88]
Hi there. I'm going through the `README.md` to try and get cdk-clj working but the example, at least for me, fails with a jgit host key not found for github.com error. If I use `:git/url "https://github.com/StediInc/cdk-clj.git"` it works just fine.

 I couldn't track down where I might disable strict host key checking but didn't have any luck.

I'm running on an Ubuntu 16.10 VM which is a bit old so might have some odd versions of things installed.

**Comment by enocom** [comment]
Using the `https` URL is correct. If you add an SSH key to your SSH agent that is registered with GitHub, the README example should work as is, but even then, it's probably better to use the https URL. I'll update the README.
